### ISSUE TITLE
cannot convert gameScene.type to SKscene

### ISSUE THREAD

**Issue by bugbot7000** [ThiagoAM/InfiniteScrollingBackground#1]
How about a quick 3-4 min youtube video demonstrating bottom scrolling.
thanks

**Comment by ThiagoAM** [comment]
Hey, thanks for the interest in my class! At the moment I really can't make a YouTube video, but I updated the README file, it's much more clear now and it does exactly what you're trying to do! I hope that help you.

**Comment by bugbot7000** [comment]
Thanks. I figured it out.
